### PR TITLE
Add org-roam link type

### PR DESCRIPTION
**Pull request by dit7ya**
Solves #180.

### CODE REVIEW

**Comment by noctuid** [comment]
Is there a benefit to adding a new link type? If not could, you just add more to the `:vars` section of the `org-link` type?

**Comment by dit7ya** [comment]
Hey, I am figuring out that link-hint works without any extra setup for regular org-roam links. However, it does not work with org links in org-journal mode without the patch I submitted. So, maybe it is not about org-roam, rather about org-journal. Let me investigate it further and please don't merge this PR in the meantime.

**Comment by dit7ya** [comment]
Okay, so it was about org-journal only, and adding `org-journal-mode` to the :vars solves it. I am closing this PR and opening another one with correct title.

**Comment by akirak** [comment]
> Hey, I am figuring out that link-hint works without any extra setup for regular org-roam links. However, it does not work with org links in org-journal mode without the patch I submitted. So, maybe it is not about org-roam, rather about org-journal. Let me investigate it further and please don't merge this PR in the meantime.

org-journal defines `org-journal-mode` which is derived from `org-mode`, so you will have to add `org-journal-mode` to `:vars`.

**Pull request closed without merging**
