### PR TITLE
Add fanyi-mode to overlay-button vars

### PR DESCRIPTION
**Pull request by akirak**
This PR adds support for [fanyi.el](https://github.com/condy0919/fanyi.el). It helps looking up a word in multiple dictionaries quickly.

### CODE REVIEW

**Comment by noctuid** [comment]
Just to confirm, this doesn't work as a button but must be the overlay-button type?

**Comment by akirak** [comment]
>  this doesn't work as a button but must be the overlay-button type?

Yes, it doesn't work without this patch and works with the patch. Both text links and pronunciation icons work.

Should I add `fanyi-mode` to `:not-vars` property of `link-hint-define-type 'button`?

**Comment by noctuid** [comment]
> Should I add fanyi-mode to :not-vars property of link-hint-define-type 'button?

Yes

**Comment by akirak** [comment]
Fixed it. Thanks.

**Comment by noctuid** [comment]
Great, thanks!

**Pull request merged**
