### PR TITLE
better custom types for action-messages and types

### PR DESCRIPTION
**Pull request by xFA25E**
2021-07-01  Valeriy Litkovskyy  <vlr.ltkvsk@protonmail.com>

    * link-hint.el (link-hint-action-messages, link-hint-types): better custom types

### CODE REVIEW

**Comment by noctuid** [comment]
Will the new type for `link-hint-action-messages` allow specifying other keywords (so it can be customized for custom actions)?

**Comment by xFA25E** [comment]
Yes, of course. Those are only suggestions with default value. Plist type is fully customizable

**Comment by xFA25E** [comment]
Example

**Comment by xFA25E** [comment]
Should I also add :key-type and :value-type of symbol and string respectively?  I'm not sure if this plist is composed ONLY by keywords and strings

**Comment by xFA25E** [comment]
Added

**Review by sirikid — APPROVED** [review]
Quite big choice, but I don't know how we can express its meaning otherwise

**Comment by xFA25E** [comment]
Maybe it is better to order it alphabetically?

**Comment by noctuid** [comment]
Thanks!

**Pull request merged**
